"""Initial revision

Revision ID: 1737083151
Revises: 
Create Date: 2025-01-17 00:06:12.888390

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1737083151'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('angel',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_angel_created_at'), 'angel', ['created_at'], unique=False)
    op.create_index(op.f('ix_angel_name'), 'angel', ['name'], unique=True)
    op.create_index(op.f('ix_angel_updated_at'), 'angel', ['updated_at'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_created_at'), 'cliente', ['created_at'], unique=False)
    op.create_index(op.f('ix_cliente_updated_at'), 'cliente', ['updated_at'], unique=False)
    op.create_table('polo',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_polo_created_at'), 'polo', ['created_at'], unique=False)
    op.create_index(op.f('ix_polo_updated_at'), 'polo', ['updated_at'], unique=False)
    op.create_table('atendimento',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('id_angel', sa.Integer(), nullable=False),
    sa.Column('id_polo', sa.Integer(), nullable=False),
    sa.Column('data_limite', sa.DateTime(), nullable=False),
    sa.Column('data_de_atendimento', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_angel'], ['angel.id'], ),
    sa.ForeignKeyConstraint(['id_polo'], ['polo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimento_created_at'), 'atendimento', ['created_at'], unique=False)
    op.create_index(op.f('ix_atendimento_data_de_atendimento'), 'atendimento', ['data_de_atendimento'], unique=False)
    op.create_index(op.f('ix_atendimento_data_limite'), 'atendimento', ['data_limite'], unique=False)
    op.create_index(op.f('ix_atendimento_updated_at'), 'atendimento', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atendimento_updated_at'), table_name='atendimento')
    op.drop_index(op.f('ix_atendimento_data_limite'), table_name='atendimento')
    op.drop_index(op.f('ix_atendimento_data_de_atendimento'), table_name='atendimento')
    op.drop_index(op.f('ix_atendimento_created_at'), table_name='atendimento')
    op.drop_table('atendimento')
    op.drop_index(op.f('ix_polo_updated_at'), table_name='polo')
    op.drop_index(op.f('ix_polo_created_at'), table_name='polo')
    op.drop_table('polo')
    op.drop_index(op.f('ix_cliente_updated_at'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_created_at'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_angel_updated_at'), table_name='angel')
    op.drop_index(op.f('ix_angel_name'), table_name='angel')
    op.drop_index(op.f('ix_angel_created_at'), table_name='angel')
    op.drop_table('angel')
    # ### end Alembic commands ###
