"""Create status field for Atendimento model

Revision ID: 1738183539
Revises: 1737083152
Create Date: 2025-01-29 17:46:00.234492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1738183539'
down_revision: Union[str, None] = '1737083152'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atendimento', sa.Column('status', sa.String(), nullable=False))
    op.create_index(op.f('ix_atendimento_status'), 'atendimento', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atendimento_status'), table_name='atendimento')
    op.drop_column('atendimento', 'status')
    # ### end Alembic commands ###
